# Generated by Django 3.0.3 on 2021-03-17 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='released_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
